#!/bin/sh

R5_0=/sys/class/remoteproc/remoteproc0
R5_1=/sys/class/remoteproc/remoteproc1

echo "Make sure the R5s are not running"
echo stop >$R5_0/state 2>/dev/null
echo stop >$R5_1/state 2>/dev/null

echo "Set the firmware to use"
echo "We can run the same image on both R5s as the image uses TCM memory only"
echo zephyr-3.2-hello.elf >$R5_0/firmware
echo zephyr-3.2-hello.elf >$R5_1/firmware

echo "Start R5_0, it will print to the 2nd UART"
echo start >$R5_0/state

# sleeps are so you can see what is happening
sleep 5

echo "Start R5_1, it will also print to the 2nd UART"
echo start >$R5_1/state

sleep 5

echo "stop and start R5_1 3 times"
for i in 1 2 3; do
    echo stop  >$R5_1/state
    sleep 1
    echo start >$R5_1/state
    sleep 1
done

echo "Now stop both R5s"
echo stop  >$R5_0/state
echo stop  >$R5_1/state
