#!/bin/sh

echo "AMD Xilinx rpmsg proxy app demo"

R5_0=/sys/class/remoteproc/remoteproc0

echo "Make sure the R5 is not running"
echo stop >$R5_0/state 2>/dev/null

echo "Set the firmware to use"
echo image_rpc_demo >$R5_0/firmware

echo "Start the R5"
echo start >$R5_0/state

echo "Now run the matrix_multiply Linux application"
proxy_app


