# Helper makefile
# Make it easy to discover what you can do

help:
	@echo "OpenAMP demo Makefile"
	@echo "This makes it easy for you to discover what you can do"
	@echo "You can see how to build something and then do it own you own"
	@echo "We don't expect you to use this Makefile in your own work"
	@echo "Consider it an executable README"
	@echo
	@echo "Build targets:"
	@echo "    zephyr-r5-hello"
	@echo "    zephyr-virtio"
	@echo "    lopper-cli"
	@echo "    oe-setup-check"
	@echo
	@echo "The following build targets may take 1 to 4 hours to execute:"
	@echo "    oe-generic-arm64"
	@echo "    oe-generic-arm32"
	@echo "    oe-lopper"
	@echo
	@echo "!!!Building things is not supported yet!!"
	@echo "but you get the idea right?"
