#!/bin/bash
# demo5-setup: run as part of container setup

sudo apt-get install -y git device-tree-compiler

cd $(dirname $0)
python3 -m venv .venv
. ./.venv/bin/activate
pip3 install ruamel.yaml==0.17.40 anytree pyyaml
git clone https://github.com/devicetree-org/lopper.git -b systemdt-linaro-demo
cd lopper
pip3 install .

